### ISSUE TITLE
arrow keys not working in insert mode

### ISSUE THREAD

**Issue by devijvers** [carlosedp/vimfiles#2]
vimrc file contains set nocompatible at the top.

If I run the set nocompatible command in vim arrow keys works fine in insert mode, it's just that I have to run it each time vim starts.

I did add this line to the top of vimrc but removing that line doesn't affect the arrow key behavior:

@@ -1,4 +1,5 @@
 filetype off
+let g:pathogen_disabled = ['nerdtree']
 call pathogen#runtime_append_all_bundles()
 call pathogen#helptags()

**Comment by carlosedp** [comment]
That's weird because I use this exact config on gVim (Windows) and MacVim.

**Comment by devijvers** [comment]
I'm using vim on ubuntu 10.10.

**Comment by carlosedp** [comment]
I will try to build a Ubunto VM to test this.
